
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  application:
    name: courses


#    datasource:
#      driver-class-name: org.postresql.Driver
#      url: jdbc:postgresql://localhost:5432/students
#      useername: username
#      password: password
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  config:
    #     students-url: http://localhost:8090/api/v1/students
    students-url: http://localhost:8222/api/v1/students
